name: "Publish"

on:
  release:
    types: [published]
  push:
    branches:
      - master

env:
  GIT_TAG_NAME: 2022.01.01

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master

  publish:
    name: Publish builder
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0

      - uses: olegtarasov/get-tag@v2.1
        #if: github.event_name == 'release'
        name: Set tag envronment variable

#      - name: Login to DockerHub
#        uses: docker/login-action@v1.12.0
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ${{ matrix.architecture }} builder
        uses: ./
        with:
          args: |
            --${{ matrix.architecture }} \
            --target /data \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --image ${{ matrix.architecture }}-builder \
            --additional-tag $GIT_TAG_NAME \
            --generic $GIT_TAG_NAME
